import { Service } from '../types';

export const SERVICES: Service[] = [
  // Production Services
  {
    id: 'ai-environment-setup',
    name: 'AI Environment Setup',
    description: 'Complete AI infrastructure and environment configuration for your projects.',
    icon: '⚡',
    gradient: 'tech-primary',
    category: 'production',
    formRoute: '/request/ai-environment-setup',
    customFields: [
      {
        name: 'aiPlatform',
        label: 'AI Platform Preference',
        type: 'select',
        required: true,
        placeholder: 'Select AI platform',
        options: [
          { value: 'openai', label: 'OpenAI' },
          { value: 'anthropic', label: 'Anthropic/Claude' },
          { value: 'google-ai', label: 'Google AI' },
          { value: 'azure-ai', label: 'Azure AI' },
          { value: 'aws-bedrock', label: 'AWS Bedrock' },
          { value: 'custom', label: 'Custom/Other' },
        ],
      },
      {
        name: 'useCase',
        label: 'Primary Use Case',
        type: 'textarea',
        required: true,
        placeholder: 'Describe your AI use case and goals...',
      },
    ],
  },
  {
    id: 'clone-video',
    name: 'Clone Video',
    description: 'AI-powered video cloning and deepfake technology services.',
    icon: '🎬',
    gradient: 'tech-primary',
    category: 'production',
    formRoute: '/request/clone-video',
    customFields: [
      {
        name: 'videoType',
        label: 'Video Type',
        type: 'select',
        required: true,
        placeholder: 'Select video type',
        options: [
          { value: 'portrait', label: 'Portrait/Person' },
          { value: 'product', label: 'Product' },
          { value: 'character', label: 'Character' },
          { value: 'voice-sync', label: 'Voice Synchronization' },
          { value: 'other', label: 'Other' },
        ],
      },
      {
        name: 'duration',
        label: 'Estimated Duration',
        type: 'text',
        required: false,
        placeholder: 'e.g., 30 seconds, 2 minutes',
      },
      {
        name: 'reference',
        label: 'Reference Material Available',
        type: 'select',
        required: true,
        placeholder: 'Select option',
        options: [
          { value: 'yes', label: 'Yes, I have reference materials' },
          { value: 'no', label: 'No, need help gathering materials' },
        ],
      },
    ],
  },
  {
    id: 'clone-audio',
    name: 'Clone Audio',
    description: 'AI voice cloning and audio synthesis services for realistic voice replication.',
    icon: '🎤',
    gradient: 'tech-primary',
    category: 'production',
    formRoute: '/request/clone-audio',
    customFields: [
      {
        name: 'voiceType',
        label: 'Voice Type',
        type: 'select',
        required: true,
        placeholder: 'Select voice type',
        options: [
          { value: 'male', label: 'Male Voice' },
          { value: 'female', label: 'Female Voice' },
          { value: 'character', label: 'Character Voice' },
          { value: 'narrator', label: 'Narrator Voice' },
        ],
      },
      {
        name: 'audioLength',
        label: 'Estimated Audio Length',
        type: 'text',
        required: false,
        placeholder: 'e.g., 1 minute, 5 minutes',
      },
      {
        name: 'sampleAvailable',
        label: 'Voice Sample Available',
        type: 'select',
        required: true,
        placeholder: 'Select option',
        options: [
          { value: 'yes', label: 'Yes, I have voice samples' },
          { value: 'no', label: 'No, need guidance' },
        ],
      },
    ],
  },
  {
    id: 'logo-concept-video',
    name: 'Logo Concept Video',
    description: 'Animated logo concepts and motion graphics for brand identity.',
    icon: '🎨',
    gradient: 'tech-primary',
    category: 'production',
    formRoute: '/request/logo-concept-video',
    customFields: [
      {
        name: 'logoStatus',
        label: 'Logo Status',
        type: 'select',
        required: true,
        placeholder: 'Select status',
        options: [
          { value: 'has-logo', label: 'I have an existing logo' },
          { value: 'needs-design', label: 'Need logo designed first' },
          { value: 'concept-only', label: 'Concept development' },
        ],
      },
      {
        name: 'style',
        label: 'Animation Style',
        type: 'select',
        required: true,
        placeholder: 'Select style',
        options: [
          { value: 'minimal', label: 'Minimal & Clean' },
          { value: 'dynamic', label: 'Dynamic & Bold' },
          { value: 'elegant', label: 'Elegant & Sophisticated' },
          { value: 'tech', label: 'Tech/Modern' },
        ],
      },
      {
        name: 'usage',
        label: 'Primary Usage',
        type: 'text',
        required: false,
        placeholder: 'e.g., website intro, social media, presentations',
      },
    ],
  },
  {
    id: 'service-concept-video',
    name: 'Service Concept Video',
    description: 'Explainer videos and concept animations showcasing your services.',
    icon: '📹',
    gradient: 'tech-primary',
    category: 'production',
    formRoute: '/request/service-concept-video',
    customFields: [
      {
        name: 'serviceType',
        label: 'Service Type',
        type: 'select',
        required: true,
        placeholder: 'Select service type',
        options: [
          { value: 'explainer', label: 'Explainer Video' },
          { value: 'promo', label: 'Promotional Video' },
          { value: 'tutorial', label: 'Tutorial/Demo' },
          { value: 'testimonial', label: 'Testimonial Video' },
        ],
      },
      {
        name: 'videoLength',
        label: 'Desired Video Length',
        type: 'select',
        required: true,
        placeholder: 'Select length',
        options: [
          { value: '15-30', label: '15-30 seconds' },
          { value: '30-60', label: '30-60 seconds' },
          { value: '1-2', label: '1-2 minutes' },
          { value: '2+', label: '2+ minutes' },
        ],
      },
      {
        name: 'targetAudience',
        label: 'Target Audience',
        type: 'text',
        required: false,
        placeholder: 'Describe your target audience...',
      },
    ],
  },
  {
    id: 'digital-ads',
    name: 'Digital Ads',
    description: 'Professional digital advertising campaigns and creative assets.',
    icon: '📊',
    gradient: 'tech-primary',
    category: 'production',
    formRoute: '/request/digital-ads',
    customFields: [
      {
        name: 'adPlatform',
        label: 'Advertising Platform',
        type: 'select',
        required: true,
        placeholder: 'Select platform',
        options: [
          { value: 'google', label: 'Google Ads' },
          { value: 'facebook', label: 'Facebook/Instagram' },
          { value: 'linkedin', label: 'LinkedIn' },
          { value: 'twitter', label: 'Twitter/X' },
          { value: 'tiktok', label: 'TikTok' },
          { value: 'multi', label: 'Multiple Platforms' },
        ],
      },
      {
        name: 'adFormat',
        label: 'Ad Format',
        type: 'select',
        required: true,
        placeholder: 'Select format',
        options: [
          { value: 'display', label: 'Display/Banner Ads' },
          { value: 'video', label: 'Video Ads' },
          { value: 'carousel', label: 'Carousel Ads' },
          { value: 'story', label: 'Story Ads' },
        ],
      },
      {
        name: 'campaignGoal',
        label: 'Campaign Goal',
        type: 'textarea',
        required: false,
        placeholder: 'Describe your campaign objectives...',
      },
    ],
  },
  {
    id: 'social-media-setup',
    name: 'Social Media Account Setup & Support',
    description: 'Complete social media account setup, optimization, and ongoing support.',
    icon: '📱',
    gradient: 'tech-primary',
    category: 'production',
    formRoute: '/request/social-media-setup',
    customFields: [
      {
        name: 'platforms',
        label: 'Platforms Needed',
        type: 'select',
        required: true,
        placeholder: 'Select platforms',
        options: [
          { value: 'facebook', label: 'Facebook' },
          { value: 'instagram', label: 'Instagram' },
          { value: 'twitter', label: 'Twitter/X' },
          { value: 'linkedin', label: 'LinkedIn' },
          { value: 'tiktok', label: 'TikTok' },
          { value: 'youtube', label: 'YouTube' },
          { value: 'multiple', label: 'Multiple Platforms' },
        ],
      },
      {
        name: 'supportType',
        label: 'Support Type',
        type: 'select',
        required: true,
        placeholder: 'Select support type',
        options: [
          { value: 'setup-only', label: 'Setup Only' },
          { value: 'setup-content', label: 'Setup + Content Strategy' },
          { value: 'ongoing', label: 'Ongoing Support' },
        ],
      },
      {
        name: 'brandInfo',
        label: 'Brand Information',
        type: 'textarea',
        required: false,
        placeholder: 'Provide key brand information, tone, and style preferences...',
      },
    ],
  },
  {
    id: 'editing-content',
    name: 'Editing Content',
    description: 'Professional content editing services for videos, images, and multimedia.',
    icon: '✂️',
    gradient: 'tech-primary',
    category: 'production',
    formRoute: '/request/editing-content',
    customFields: [
      {
        name: 'contentType',
        label: 'Content Type',
        type: 'select',
        required: true,
        placeholder: 'Select content type',
        options: [
          { value: 'video', label: 'Video Editing' },
          { value: 'photo', label: 'Photo Editing' },
          { value: 'graphics', label: 'Graphics Design' },
          { value: 'mixed', label: 'Mixed Media' },
        ],
      },
      {
        name: 'editType',
        label: 'Editing Type',
        type: 'select',
        required: true,
        placeholder: 'Select editing type',
        options: [
          { value: 'basic', label: 'Basic Editing' },
          { value: 'advanced', label: 'Advanced Editing' },
          { value: 'color-grading', label: 'Color Grading' },
          { value: 'full-production', label: 'Full Production' },
        ],
      },
      {
        name: 'volume',
        label: 'Estimated Volume',
        type: 'text',
        required: false,
        placeholder: 'e.g., 10 videos per month, one-time project',
      },
    ],
  },
  // Development Services
  {
    id: 'network-setup',
    name: 'Network Setup Guide & Support',
    description: 'Network configuration, setup guides, and technical support services.',
    icon: '🌐',
    gradient: 'tech-secondary',
    category: 'development',
    formRoute: '/request/network-setup',
    customFields: [
      {
        name: 'networkType',
        label: 'Network Type',
        type: 'select',
        required: true,
        placeholder: 'Select network type',
        options: [
          { value: 'office', label: 'Office Network' },
          { value: 'home', label: 'Home Network' },
          { value: 'server', label: 'Server Infrastructure' },
          { value: 'cloud', label: 'Cloud Network' },
          { value: 'vpn', label: 'VPN Setup' },
        ],
      },
      {
        name: 'supportLevel',
        label: 'Support Level Needed',
        type: 'select',
        required: true,
        placeholder: 'Select support level',
        options: [
          { value: 'guide-only', label: 'Setup Guide Only' },
          { value: 'remote-support', label: 'Remote Support' },
          { value: 'on-site', label: 'On-Site Support' },
          { value: 'consultation', label: 'Consultation' },
        ],
      },
      {
        name: 'currentSetup',
        label: 'Current Network Setup',
        type: 'textarea',
        required: false,
        placeholder: 'Describe your current network configuration...',
      },
    ],
  },
  {
    id: 'custom-pages',
    name: 'Custom Pages',
    description: 'Custom web page development tailored to your specific needs.',
    icon: '📄',
    gradient: 'tech-secondary',
    category: 'development',
    formRoute: '/request/custom-pages',
    customFields: [
      {
        name: 'pageType',
        label: 'Page Type',
        type: 'select',
        required: true,
        placeholder: 'Select page type',
        options: [
          { value: 'landing', label: 'Landing Page' },
          { value: 'product', label: 'Product Page' },
          { value: 'service', label: 'Service Page' },
          { value: 'about', label: 'About Page' },
          { value: 'custom', label: 'Custom Page' },
        ],
      },
      {
        name: 'framework',
        label: 'Preferred Framework',
        type: 'select',
        required: true,
        placeholder: 'Select framework',
        options: [
          { value: 'react', label: 'React' },
          { value: 'nextjs', label: 'Next.js' },
          { value: 'vue', label: 'Vue.js' },
          { value: 'html-css', label: 'HTML/CSS' },
          { value: 'wordpress', label: 'WordPress' },
          { value: 'no-preference', label: 'No Preference' },
        ],
      },
      {
        name: 'features',
        label: 'Required Features',
        type: 'textarea',
        required: false,
        placeholder: 'List key features and functionality needed...',
      },
    ],
  },
  {
    id: 'business-form-setup',
    name: 'Business Form Setup',
    description: 'Custom business forms and form automation solutions.',
    icon: '📋',
    gradient: 'tech-secondary',
    category: 'development',
    formRoute: '/request/business-form-setup',
    customFields: [
      {
        name: 'formType',
        label: 'Form Type',
        type: 'select',
        required: true,
        placeholder: 'Select form type',
        options: [
          { value: 'contact', label: 'Contact Form' },
          { value: 'lead', label: 'Lead Generation' },
          { value: 'survey', label: 'Survey Form' },
          { value: 'order', label: 'Order/Booking' },
          { value: 'feedback', label: 'Feedback Form' },
          { value: 'custom', label: 'Custom Form' },
        ],
      },
      {
        name: 'integration',
        label: 'Integration Needs',
        type: 'select',
        required: true,
        placeholder: 'Select integration',
        options: [
          { value: 'email', label: 'Email Integration' },
          { value: 'crm', label: 'CRM Integration' },
          { value: 'database', label: 'Database Storage' },
          { value: 'payment', label: 'Payment Gateway' },
          { value: 'multiple', label: 'Multiple Integrations' },
        ],
      },
      {
        name: 'formFields',
        label: 'Form Fields & Requirements',
        type: 'textarea',
        required: false,
        placeholder: 'Describe the fields and data collection needs...',
      },
    ],
  },
  {
    id: 'newsletters',
    name: 'Newsletters',
    description: 'Newsletter design, setup, and email marketing automation.',
    icon: '📧',
    gradient: 'tech-secondary',
    category: 'development',
    formRoute: '/request/newsletters',
    customFields: [
      {
        name: 'serviceType',
        label: 'Service Type',
        type: 'select',
        required: true,
        placeholder: 'Select service type',
        options: [
          { value: 'setup-only', label: 'Newsletter Setup Only' },
          { value: 'design', label: 'Design & Setup' },
          { value: 'template', label: 'Template Creation' },
          { value: 'automation', label: 'Automation Setup' },
          { value: 'full-service', label: 'Full Service' },
        ],
      },
      {
        name: 'platform',
        label: 'Email Platform',
        type: 'select',
        required: true,
        placeholder: 'Select platform',
        options: [
          { value: 'mailchimp', label: 'Mailchimp' },
          { value: 'sendgrid', label: 'SendGrid' },
          { value: 'constant-contact', label: 'Constant Contact' },
          { value: 'convertkit', label: 'ConvertKit' },
          { value: 'custom', label: 'Custom Solution' },
          { value: 'no-preference', label: 'No Preference' },
        ],
      },
      {
        name: 'frequency',
        label: 'Newsletter Frequency',
        type: 'text',
        required: false,
        placeholder: 'e.g., Weekly, Monthly, Quarterly',
      },
    ],
  },
  {
    id: 'email-setup',
    name: 'Email Setup',
    description: 'Professional email configuration and business email setup services.',
    icon: '✉️',
    gradient: 'tech-secondary',
    category: 'development',
    formRoute: '/request/email-setup',
    customFields: [
      {
        name: 'emailType',
        label: 'Email Type',
        type: 'select',
        required: true,
        placeholder: 'Select email type',
        options: [
          { value: 'business', label: 'Business Email (Gmail/Outlook)' },
          { value: 'custom-domain', label: 'Custom Domain Email' },
          { value: 'mail-server', label: 'Mail Server Setup' },
          { value: 'forwarding', label: 'Email Forwarding' },
        ],
      },
      {
        name: 'emailCount',
        label: 'Number of Email Addresses',
        type: 'select',
        required: true,
        placeholder: 'Select count',
        options: [
          { value: '1-5', label: '1-5 addresses' },
          { value: '6-10', label: '6-10 addresses' },
          { value: '11-25', label: '11-25 addresses' },
          { value: '25+', label: '25+ addresses' },
        ],
      },
      {
        name: 'currentSetup',
        label: 'Current Email Setup',
        type: 'textarea',
        required: false,
        placeholder: 'Describe your current email configuration...',
      },
    ],
  },
  {
    id: 'domain-configure',
    name: 'Domain Configure',
    description: 'Domain configuration, DNS setup, and domain management services.',
    icon: '🔗',
    gradient: 'tech-secondary',
    category: 'development',
    formRoute: '/request/domain-configure',
    customFields: [
      {
        name: 'serviceType',
        label: 'Service Type',
        type: 'select',
        required: true,
        placeholder: 'Select service type',
        options: [
          { value: 'dns-setup', label: 'DNS Configuration' },
          { value: 'domain-transfer', label: 'Domain Transfer' },
          { value: 'ssl-setup', label: 'SSL Certificate Setup' },
          { value: 'subdomain', label: 'Subdomain Setup' },
          { value: 'full-config', label: 'Full Domain Configuration' },
        ],
      },
      {
        name: 'domainProvider',
        label: 'Domain Provider',
        type: 'text',
        required: false,
        placeholder: 'e.g., GoDaddy, Namecheap, Google Domains',
      },
      {
        name: 'domainName',
        label: 'Domain Name',
        type: 'text',
        required: false,
        placeholder: 'yourdomain.com',
      },
    ],
  },
  {
    id: 'tailored-development',
    name: 'Tailored Development Tasks',
    description: 'Custom development solutions tailored to your specific requirements.',
    icon: '⚙️',
    gradient: 'tech-secondary',
    category: 'development',
    formRoute: '/request/tailored-development',
    customFields: [
      {
        name: 'projectType',
        label: 'Project Type',
        type: 'select',
        required: true,
        placeholder: 'Select project type',
        options: [
          { value: 'web-app', label: 'Web Application' },
          { value: 'api', label: 'API Development' },
          { value: 'integration', label: 'System Integration' },
          { value: 'automation', label: 'Automation Script' },
          { value: 'custom', label: 'Custom Development' },
        ],
      },
      {
        name: 'techStack',
        label: 'Preferred Tech Stack',
        type: 'text',
        required: false,
        placeholder: 'e.g., Node.js, Python, React, etc.',
      },
      {
        name: 'requirements',
        label: 'Project Requirements',
        type: 'textarea',
        required: true,
        placeholder: 'Describe your project requirements in detail...',
      },
    ],
  },
];
